#include <gtest/gtest.h>

#include "cli/fs_updater_error.h"

#include <set>

namespace {

template <typename E>
constexpr int code(E v) { return static_cast<int>(v); }

TEST(FsUpdaterError, FirmwareSuccessMatchesPosixExitZero)
{
    EXPECT_EQ(code(UPDATER_FIRMWARE_STATE::UPDATE_SUCCESSFUL), 0);
}

TEST(FsUpdaterError, UnhandledExceptionMatchesProcessAbort)
{
    EXPECT_EQ(code(UPDATER_FATAL::UNHANDLED_EXCEPTION), 124);
}

// Scripted callers key on these numbers; renumbering is an interface break.
TEST(FsUpdaterError, IndeterminateAndUnprovisionedArePinned)
{
    EXPECT_EQ(code(UPDATER_UPDATE_REBOOT_STATE::UPDATE_REBOOT_STATE_INDETERMINATE), 55);
    EXPECT_EQ(code(UPDATER_SETGET_UPDATE_STATE::UPDATE_STATE_UNPROVISIONED), 56);
    EXPECT_EQ(code(UPDATER_UPDATE_REBOOT_STATE::ROLLBACK_APP_REBOOT_INDETERMINATE), 57);
}

TEST(FsUpdaterError, AllExitCodesAreDistinct)
{
    const std::set<int> all_codes = {
        code(UPDATER_FIRMWARE_STATE::UPDATE_SUCCESSFUL),
        code(UPDATER_FIRMWARE_STATE::UPDATE_PROGRESS_ERROR),
        code(UPDATER_FIRMWARE_STATE::UPDATE_INTERNAL_ERROR),
        code(UPDATER_FIRMWARE_STATE::UPDATE_SYSTEM_ERROR),

        code(UPDATER_APPLICATION_STATE::UPDATE_SUCCESSFUL),
        code(UPDATER_APPLICATION_STATE::UPDATE_PROGRESS_ERROR),
        code(UPDATER_APPLICATION_STATE::UPDATE_INTERNAL_ERROR),
        code(UPDATER_APPLICATION_STATE::UPDATE_SYSTEM_ERROR),

        code(UPDATER_FIRMWARE_AND_APPLICATION_STATE::UPDATE_SUCCESSFUL),
        code(UPDATER_FIRMWARE_AND_APPLICATION_STATE::UPDATE_PROGRESS_ERROR),
        code(UPDATER_FIRMWARE_AND_APPLICATION_STATE::UPDATE_INTERNAL_ERROR),
        code(UPDATER_FIRMWARE_AND_APPLICATION_STATE::UPDATE_SYSTEM_ERROR),

        code(UPDATER_UPDATE_ROLLBACK_STATE::UPDATE_ROLLBACK_SUCCESSFUL),
        code(UPDATER_UPDATE_ROLLBACK_STATE::UPDATE_ROLLBACK_PROGRESS_ERROR),
        code(UPDATER_UPDATE_ROLLBACK_STATE::UPDATE_ROLLBACK_INTERNAL_ERROR),
        code(UPDATER_UPDATE_ROLLBACK_STATE::UPDATE_ROLLBACK_SYSTEM_ERROR),

        code(UPDATER_COMMIT_STATE::UPDATE_COMMIT_SUCCESSFUL),
        code(UPDATER_COMMIT_STATE::UPDATE_NOT_NEEDED),
        code(UPDATER_COMMIT_STATE::UPDATE_NOT_ALLOWED_UBOOT_STATE),
        code(UPDATER_COMMIT_STATE::UPDATE_SYSTEM_ERROR),

        code(UPDATER_UPDATE_REBOOT_STATE::FAILED_APP_UPDATE),
        code(UPDATER_UPDATE_REBOOT_STATE::FAILED_FW_UPDATE),
        code(UPDATER_UPDATE_REBOOT_STATE::FW_UPDATE_REBOOT_FAILED),
        code(UPDATER_UPDATE_REBOOT_STATE::INCOMPLETE_FW_UPDATE),
        code(UPDATER_UPDATE_REBOOT_STATE::INCOMPLETE_APP_UPDATE),
        code(UPDATER_UPDATE_REBOOT_STATE::INCOMPLETE_APP_FW_UPDATE),
        code(UPDATER_UPDATE_REBOOT_STATE::UPDATE_REBOOT_PENDING),
        code(UPDATER_UPDATE_REBOOT_STATE::NO_UPDATE_REBOOT_PENDING),
        code(UPDATER_UPDATE_REBOOT_STATE::ROLLBACK_FW_REBOOT_PENDING),
        code(UPDATER_UPDATE_REBOOT_STATE::ROLLBACK_APP_REBOOT_PENDING),
        code(UPDATER_UPDATE_REBOOT_STATE::ROLLBACK_APP_FW_REBOOT_PENDING),
        code(UPDATER_UPDATE_REBOOT_STATE::INCOMPLETE_FW_ROLLBACK),
        code(UPDATER_UPDATE_REBOOT_STATE::INCOMPLETE_APP_ROLLBACK),
        code(UPDATER_UPDATE_REBOOT_STATE::INCOMPLETE_APP_FW_ROLLBACK),
        code(UPDATER_UPDATE_REBOOT_STATE::UPDATE_REBOOT_STATE_INDETERMINATE),
        code(UPDATER_UPDATE_REBOOT_STATE::ROLLBACK_APP_REBOOT_INDETERMINATE),

        code(UPDATER_IS_UPDATE_AVAILABLE_STATE::NO_UPDATE_AVAILABLE),
        code(UPDATER_IS_UPDATE_AVAILABLE_STATE::FIRMWARE_UPDATE_AVAILABLE),
        code(UPDATER_IS_UPDATE_AVAILABLE_STATE::APPLICATION_UPDATE_AVAILABLE),
        code(UPDATER_IS_UPDATE_AVAILABLE_STATE::FIRMWARE_AND_APPLICATION_UPDATE_AVAILABLE),

        code(UPDATER_DOWNLOAD_UPDATE_STATE::NO_DOWNLOAD_QUEUED),
        code(UPDATER_DOWNLOAD_UPDATE_STATE::UPDATE_DOWNLOAD_STARTED),
        code(UPDATER_DOWNLOAD_UPDATE_STATE::UPDATE_DOWNLOAD_STARTED_BEFORE),
        code(UPDATER_DOWNLOAD_UPDATE_STATE::UPDATE_DOWNLOAD_FAILED),

        code(UPDATER_DOWNLOAD_PROGRESS_STATE::NO_DOWNLOAD_STARTED),
        code(UPDATER_DOWNLOAD_PROGRESS_STATE::UPDATE_DOWNLOAD_WAITING_TO_START),
        code(UPDATER_DOWNLOAD_PROGRESS_STATE::UPDATE_DOWNLOAD_IN_PROGRESS),
        code(UPDATER_DOWNLOAD_PROGRESS_STATE::UPDATE_DOWNLOAD_FINISHED),

        code(UPDATER_INSTALL_UPDATE_STATE::NO_INSTALLATION_QUEUED),
        code(UPDATER_INSTALL_UPDATE_STATE::UPDATE_INSTALLATION_IN_PROGRESS),
        code(UPDATER_INSTALL_UPDATE_STATE::UPDATE_INSTALLATION_FINISHED),
        code(UPDATER_INSTALL_UPDATE_STATE::UPDATE_INSTALLATION_FAILED),

        code(UPDATER_APPLY_UPDATE_STATE::APPLY_SUCCESSFUL),
        code(UPDATER_APPLY_UPDATE_STATE::APPLY_FAILED),

        code(UPDATER_SETGET_UPDATE_STATE::GETSET_STATE_SUCCESSFUL),
        code(UPDATER_SETGET_UPDATE_STATE::PASSING_PARAM_UPDATE_STATE_WRONG),
        code(UPDATER_SETGET_UPDATE_STATE::UPDATE_STATE_BAD),
        code(UPDATER_SETGET_UPDATE_STATE::UPDATE_STATE_UNPROVISIONED),

        code(UPDATER_CLI_VALIDATION::INVALID_UPDATE_TYPE),
        code(UPDATER_CLI_VALIDATION::UPDATE_FILE_NOT_FOUND),
        code(UPDATER_CLI_VALIDATION::MISSING_ENV_UPDATE_STICK),
        code(UPDATER_CLI_VALIDATION::MISSING_ENV_UPDATE_FILE),
        code(UPDATER_CLI_VALIDATION::UPDATE_TYPE_WITHOUT_FILE),
        code(UPDATER_CLI_VALIDATION::INCOMPATIBLE_ARG_COMBO),
        code(UPDATER_CLI_VALIDATION::INSTALL_BUSY),
        code(UPDATER_CLI_VALIDATION::PERMISSION_DENIED),

        code(UPDATER_SYSTEM::REBOOT_FAILED),

        code(UPDATER_FATAL::UNHANDLED_EXCEPTION),
    };

    // Add every new enumerator here too: this set is the whole-table drift
    // guard and does not derive from fs_updater_error.h automatically.
    EXPECT_EQ(all_codes.size(), 68u);
}

TEST(FsUpdaterError, AllExitCodesFitInUnsignedByteSpace)
{
    // CLI exit codes are returned via process exit status; POSIX truncates to
    // 8 bits. Codes outside 0..255 would silently alias.
    EXPECT_LE(code(UPDATER_FATAL::UNHANDLED_EXCEPTION), 255);
    EXPECT_GE(code(UPDATER_FIRMWARE_STATE::UPDATE_SUCCESSFUL), 0);
}

} // namespace
