#pragma once

enum class UPDATER_FIRMWARE_STATE : int{
    UPDATE_SUCCESSFUL = 0,
    UPDATE_PROGRESS_ERROR = 1,
    UPDATE_INTERNAL_ERROR = 2,
    UPDATE_SYSTEM_ERROR = 3,
    ROLLBACK_SUCCESSFUL = 4,
    ROLLBACK_PROGRESS_ERROR = 5,
    ROLLBACK_INTERNAL_ERROR = 6,
    ROLLBACK_SYSTEM_ERROR = 7,
};

enum class UPDATER_APPLICATION_STATE : int{
    UPDATE_SUCCESSFUL = 8,
    UPDATE_PROGRESS_ERROR = 9,
    UPDATE_INTERNAL_ERROR = 10,
    UPDATE_SYSTEM_ERROR = 11,
    ROLLBACK_SUCCESSFUL = 12,
    ROLLBACK_PROGRESS_ERROR = 13,
    ROLLBACK_INTERNAL_ERROR = 14,
    ROLLBACK_SYSTEM_ERROR = 15
};

enum class UPDATER_FIRMWARE_AND_APPLICATION_STATE : int{
    UPDATE_SUCCESSFUL = 16,
    UPDATE_PROGRESS_ERROR = 17,
    UPDATE_INTERNAL_ERROR = 18,
    UPDATE_SYSTEM_ERROR = 19
};

enum class UPDATER_COMMIT_STATE : int{
    SUCCESSFUL = 20,
    UPDATE_NOT_NEEDED = 21,
    UPDATE_NOT_ALLOWED_UBOOT_STATE = 22,
    UPDATE_SYSTEM_ERROR = 23
};

enum class UPDATER_UPDATE_REBOOT_STATE : int{
    FAILED_APP_UPDATE = 24,
    FAILED_FW_UPDATE = 25,
    FW_UPDATE_REBOOT_FAILED = 26,
    INCOMPLETE_FW_UPDATE = 27,
    INCOMPLETE_APP_UPDATE = 28,
    INCOMPLETE_APP_FW_UPDATE = 29,
    NO_UPDATE_REBOOT_PENDING = 30,
    ROLLBACK_FW_REBOOT_PENDING = 31,
    ROLLBACK_APP_REBOOT_PENDING = 32,
    INCOMPLETE_FW_ROLLBACK = 33,
    INCOMPLETE_APP_ROLLBACK = 34
};

enum class UPDATER_AUTOMATIC_UPDATE_FIRMWARE_STATE : int{
    UPDATE_SUCCESSFULL = 35,
    UPDATE_PROGRESS_ERROR = 36,
    UPDATE_INTERNAL_ERROR = 37,
    UPDATE_SYSTEM_ERROR = 38
};

enum class UPDATER_AUTOMATIC_UPDATE_APPLICATION_STATE : int{
    UPDATE_SUCCESSFULL = 39,
    UPDATE_PROGRESS_ERROR = 40,
    UPDATE_INTERNAL_ERROR = 41,
    UPDATE_SYSTEM_ERROR = 42
};

enum class UPDATER_AUTOMATIC_UPDATE_FIRMWARE_AND_APPLICATION_STATE : int{
    UPDATE_SUCCESSFULL = 43,
    UPDATE_PROGRESS_ERROR = 44,
    UPDATE_INTERNAL_ERROR = 45,
    UPDATE_SYSTEM_ERROR = 46
};

enum class UPDATER_ALLOW_AUTOMATIC_UPDATE_STATE : int{
    UPDATE_SUCCESSFULL = 47,
    FORMER_APPLICATION_UPDATE_FAILED = 48,
    FORMER_FIRMWARE_UPDATE_FAILED = 49,
    FORMER_FIRMWARE_REBOOT_FAILED = 50
};

enum class UPDATER_IS_UPDATE_AVAILABLE_STATE : int{
    NO_UPDATE_AVAILABLE = 51,
    FIRMWARE_UPDATE_AVAILABLE = 52,
    APPLICATION_UPDATE_AVAILABLE = 53,
    FIRMWARE_AND_APPLICATION_UPDATE_AVAILABLE = 54
};

enum class UPDATER_DOWNLOAD_FIRMWARE_UPDATE_STATE : int{
    NO_DOWNLOAD_QUEUED = 55,
    FIRMWARE_DOWNLOAD_STARTED = 56,
    FIRMWARE_DOWNLOAD_STARTED_BEFORE = 57
};

enum class UPDATER_DOWNLOAD_APPLICATION_UPDATE_STATE : int{
    NO_DOWNLOAD_QUEUED = 58,
    APPLICATION_DOWNLOAD_STARTED = 59,
    APPLICATION_DOWNLOAD_STARTED_BEFORE = 60
};

enum class UPDATER_DOWNLOAD_PROGRESS_STATE : int{
    NO_DOWNLOAD_STARTED = 61,
    FIRMWARE_DOWNLOAD_IN_PROGRESS = 62,
	APPLICATION_DOWNLOAD_IN_PROGRESS = 63,
    FIRMWARE_AND_APPLICATION_DOWNLOAD_IN_PROGRESS = 64,
    ALL_REQUESTED_DOWNLOADS_FINISHED = 65
};

enum class UPDATER_INSTALL_FIRMWARE_UPDATE_STATE : int{
    NO_INSTALLATION_QUEUED = 66,
    FIRMWARE_INSTALLATION_IN_PROGRESS = 67,
    FIRMWARE_INSTALLATION_FINISHED = 68,                //TODO unused
    FIRMWARE_INSTALLATION_FAILED = 69
};

enum class UPDATER_INSTALL_APPLICATION_UPDATE_STATE : int{
    NO_INSTALLATION_QUEUED = 70,
    APPLICATION_INSTALLATION_IN_PROGRESS = 71,
    APPLICATION_INSTALLATION_FINISHED = 72,                //TODO unused
    APPLICATION_INSTALLATION_FAILED = 73
};

enum class UPDATER_APPLY_UPDATE_STATE : int{
    APPLY_SUCCESSFULL = 74,
    APPLY_FAILED = 75
};

enum class UPDATER_SETGET_UPDATE_STATE : int{
    GETSET_STATE_SUCCESSFULL = 76,
    PASSING_PARAM_UPDATE_STATE_WRONG = 77,
    UPDATE_STATE_BAD = 78
};
