#pragma once

enum class UPDATER_FIRMWARE_STATE : int{
    UPDATE_SUCCESSFUL = 0,
    UPDATE_PROGRESS_ERROR = 1,
    UPDATE_INTERNAL_ERROR = 2,
    UPDATE_SYSTEM_ERROR = 3,
    ROLLBACK_SUCCESSFUL = 4,
    ROLLBACK_PROGRESS_ERROR = 5,
    ROLLBACK_INTERNAL_ERROR = 6,
    ROLLBACK_SYSTEM_ERROR = 7,
};

enum class UPDATER_APPLICATION_STATE : int{
    UPDATE_SUCCESSFUL = 8,
    UPDATE_PROGRESS_ERROR = 9,
    UPDATE_INTERNAL_ERROR = 10,
    UPDATE_SYSTEM_ERROR = 11,
    ROLLBACK_SUCCESSFUL = 12,
    ROLLBACK_PROGRESS_ERROR = 13,
    ROLLBACK_INTERNAL_ERROR = 14,
    ROLLBACK_SYSTEM_ERROR = 15
};

enum class UPDATER_FIRMWARE_AND_APPLICATION_STATE : int{
    UPDATE_SUCCESSFUL = 16,
    UPDATE_PROGRESS_ERROR = 17,
    UPDATE_INTERNAL_ERROR = 18,
    UPDATE_SYSTEM_ERROR = 19
};

enum class UPDATER_COMMIT_STATE : int{
    SUCCESSFUL = 20,
    UPDATE_NOT_NEEDED = 21,
    UPDATE_NOT_ALLOWED_UBOOT_STATE = 22,
    UPDATE_SYSTEM_ERROR = 23
};

enum class UPDATER_UPDATE_REBOOT_STATE : int{
    FAILED_APP_UPDATE = 21,
    FAILED_FW_UPDATE = 22,
    FW_UPDATE_REBOOT_FAILED = 23,
    INCOMPLETE_FW_UPDATE = 24,
    INCOMPLETE_APP_UPDATE = 25,
    INCOMPLETE_APP_FW_UPDATE = 26,
    NO_UPDATE_REBOOT_PENDING = 27,
    ROLLBACK_FW_REBOOT_PENDING = 28,
    ROLLBACK_APP_REBOOT_PENDING = 29
};

enum class UPDATER_AUTOMATIC_UPDATE_FIRMWARE_STATE : int{
    UPDATE_SUCCESSFULL = 30,
    UPDATE_PROGRESS_ERROR = 31,
    UPDATE_INTERNAL_ERROR = 32,
    UPDATE_SYSTEM_ERROR = 33
};

enum class UPDATER_AUTOMATIC_UPDATE_APPLICATION_STATE : int{
    UPDATE_SUCCESSFULL = 34,
    UPDATE_PROGRESS_ERROR = 35,
    UPDATE_INTERNAL_ERROR = 36,
    UPDATE_SYSTEM_ERROR = 37
};

enum class UPDATER_AUTOMATIC_UPDATE_FIRMWARE_AND_APPLICATION_STATE : int{
    UPDATE_SUCCESSFULL = 38,
    UPDATE_PROGRESS_ERROR = 39,
    UPDATE_INTERNAL_ERROR = 40,
    UPDATE_SYSTEM_ERROR = 41
};

enum class UPDATER_ALLOW_AUTOMATIC_UPDATE_STATE : int{
    UPDATE_SUCCESSFULL = 42,
    FORMER_APPLICATION_UPDATE_FAILED = 43,
    FORMER_FIRMWARE_UPDATE_FAILED = 44,
    FORMER_FIRMWARE_REBOOT_FAILED = 45
};
